### ISSUE TITLE
has_key? won't work for CRDT maps

### ISSUE THREAD

**Issue by shribe** [drewkerrigan/riak-elixir-client#34]
So, when using CRDT maps with register types, the underlying call has to be, for instance:

:riakc_map.is_key({<<"status">>, :register}, map)

and the in map.ex, line 68, the guard clause prevents that; I've removed the "and is_binary(key)" and it now works such that this gives the correct response:

Riak.CRDT.Map.has_key?(obj, {"status", :register})

But I'm sure that there is some checking that could still be done on the key, I just don't know what it is.

**Comment by drewkerrigan** [comment]
@schribe yes it looks like the `has_key?` implementation is a bit flawed and makes several assumptions. I think the original intention was to create a `has_key?` that can iterate all keys (regardless of type) so that it's easier to find keys, but I think requiring the type will be simpler and makes more sense in this context anyway.
